general {
  hide_cursor = true
  ignore_empty_input = true
  immediate_render = true
}

background {
  monitor =
  path = screenshot
  color = rgba(25, 22, 32, 1.0)
  blur_passes = 2
  blur_size = 8
  brightness = 0.62
  vibrancy = 0.12
}

shape {
  monitor =
  size = 360, 68
  color = rgba(27, 23, 36, 0.82)
  rounding = 18
  border_size = 1
  border_color = rgba(225, 214, 255, 0.2)
  position = 0, -18
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 320, 52
  outline_thickness = 2
  dots_size = 0.22
  dots_spacing = 0.18
  dots_center = true
  outer_color = rgba(185, 156, 255, 0.9)
  inner_color = rgba(27, 23, 36, 0.9)
  font_color = rgba(247, 242, 255, 1.0)
  fade_on_empty = false
  placeholder_text = <i>Nhập mật khẩu</i>
  position = 0, -18
  halign = center
  valign = center
}

label {
  monitor =
  text = <b>Đã khóa</b>
  color = rgba(247, 242, 255, 1.0)
  font_size = 18
  position = 0, 48
  halign = center
  valign = center
}
