[color]
; Aurora / Catppuccin Mocha palette
background 	= #f21e1e2e
surface     = #313244
surface0    = #45475a
foreground 	= #cdd6f4
sep 		= #f8f8f2

rosewater   = #f4dbd6
flamingo    = #f0c6c6
pink        = #f5c2e7
mauve       = #cba6f7
red         = #f38ba8
maroon      = #eba0ac
peach       = #fab387
yellow      = #f9e2af
green       = #a6e3a1
teal        = #94e2d5
sky         = #89dceb
sapphire    = #74c7ec
blue        = #89b4fa
lavender    = #b4befe
orange 		= #fab387
purple 		= #cba6f7
